Repository theforeman/puppet-qpid, pull requests merged in 2018-07, with the labels that each got.

#91 msync: Acceptance tests update
  Gemfile
  spec/acceptance/nodesets/docker/centos-6.yml
  spec/acceptance/nodesets/docker/centos-7.yml
  spec/acceptance/nodesets/docker/debian-8.yml
  spec/acceptance/nodesets/docker/debian-9.yml
  spec/acceptance/nodesets/docker/ubuntu-14.04.yml
  spec/acceptance/nodesets/docker/ubuntu-16.04.yml
Labels: Modulesync, Needs testing, Not yet reviewed

#92 msync: rake changelog & beaker hostname
  Gemfile
  Rakefile
Labels: Needs testing, Not yet reviewed

#93 Allow camptocamp/systemd 2.x
  metadata.json
Labels: Needs testing, Not yet reviewed

#94 Release 4.2.2
  CHANGELOG.md
Labels: Needs testing, Not yet reviewed

#96 Properly handle systemd_limits
  manifests/router/service.pp
  manifests/service.pp
  spec/classes/qpid_router_config_spec.rb
  spec/classes/qpid_spec.rb
  spec/spec_helper.rb
Labels: Needs testing, Not yet reviewed

#97 Release 4.2.3
  CHANGELOG.md
Labels: Needs testing, skip-changelog

#98 Fixes #24415 - Add hello interval/max_age params to qdrouterd.
  manifests/router.pp
  manifests/router/params.pp
  spec/classes/qpid_router_config_spec.rb
  templates/router/header.conf.erb
Labels: Needs testing, Not yet reviewed

#99 msync: changelog user & custom facts in tests
  .sync.yml
  Rakefile
  spec/spec_helper.rb
Labels: Needs testing, Not yet reviewed
