Repository theforeman/puppet-qpid, pull requests merged in 2021-04, with the labels that each got.

#156 Add basic set of acceptance tests
  .github/workflows/ci.yml
  spec/acceptance/qpid_router_spec.rb
  spec/acceptance/qpid_spec.rb
  spec/acceptance/qpid_tool_spec.rb
  spec/setup_acceptance_node.pp
Labels: Needs testing, Not yet reviewed

#155 Add EL8 support
  metadata.json
  spec/setup_acceptance_node.pp
Labels: Enhancement, Needs testing, Not yet reviewed

#154 Refs #32037: Add ensure on qpid class to allow removal of all qpid as…
  manifests/config.pp
  manifests/init.pp
  manifests/install.pp
  manifests/router.pp
  manifests/router/config.pp
  manifests/router/install.pp
  manifests/router/service.pp
  manifests/service.pp
  spec/acceptance/qpid_router_spec.rb
  spec/acceptance/qpid_spec.rb
  spec/acceptance/qpid_tool_spec.rb
  spec/classes/qpid_router_spec.rb
  spec/classes/qpid_spec.rb
Labels: Needs testing, Not yet reviewed

#159 Refs #32037: Do not remove all packages when ensuring absent
  manifests/config.pp
  manifests/install.pp
  manifests/router/service.pp
  manifests/service.pp
  spec/classes/qpid_spec.rb
Labels: Bug, Needs testing, Not yet reviewed

#160 Drop Package['qpit-tools'] -> Package['qpid-cpp-server'] test case
  spec/acceptance/qpid_tool_spec.rb
Labels: Needs testing, Not yet reviewed

#158 Refs #32037: Add ensure on qpid::tools class to allow removal of package
  manifests/install.pp
  manifests/tools.pp
  spec/acceptance/qpid_spec.rb
  spec/acceptance/qpid_tool_spec.rb
  spec/classes/qpid_spec.rb
  spec/classes/qpid_tools_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#162 Fix qpid-dispatch parameter deprecation warnings
  README.md
  spec/defines/router_link_route_spec.rb
  spec/defines/router_log_spec.rb
  spec/defines/router_ssl_profile_spec.rb
  templates/router/link_route.conf.erb
  templates/router/log.conf.erb
  templates/router/ssl_profile.conf.erb
Labels: Needs testing, Not yet reviewed

#161 Refs #32037: Manage /var/lib/qpidd
  manifests/config.pp
  manifests/init.pp
  spec/acceptance/qpid_spec.rb
  spec/classes/qpid_spec.rb
  templates/qpidd.conf.erb
Labels: Enhancement, Needs testing, Not yet reviewed

#163 Release 8.0.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
