Repository theforeman/puppet-qpid, pull requests merged in 2021-03, with the labels that each got.

#145 Expose username and sasl_mechanism options in config_cmd
  manifests/config/bind.pp
  manifests/config/exchange.pp
  manifests/config/queue.pp
  manifests/config_cmd.pp
  spec/defines/config_cmd_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#146 Release 7.0.0
  CHANGELOG.md
  HISTORY.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog

#144 Update Github Actions workflow
  .github/workflows/ci.yml
  .github/workflows/cron.yml
  .github/workflows/unit.yml
  .sync.yml
  Gemfile
Labels: Modulesync, Needs testing, Not yet reviewed

#150 Remove duplicate relations
  manifests/install.pp
  spec/classes/qpid_spec.rb
Labels: Needs testing, Not yet reviewed

#148 Refs #32037: Add parameters to disable qpid services
  manifests/init.pp
  manifests/router.pp
  manifests/router/service.pp
  manifests/service.pp
  spec/classes/qpid_router_spec.rb
  spec/classes/qpid_spec.rb
Labels: Enhancement, Needs testing, Not yet reviewed

#149 Install cyrus-sasl-plain package
  manifests/install.pp
  spec/classes/qpid_spec.rb
Labels: Enhancement, Needs testing

#153 Router template should use mode and not router_mode
  spec/classes/qpid_router_spec.rb
  templates/router/header.conf.erb
Labels: Bug, Needs testing, Not yet reviewed

#152 Add types to router.pp
  manifests/router.pp
  manifests/router/params.pp
Labels: Needs testing, Not yet reviewed

#147 Support Puppet 7
  metadata.json
Labels: Needs testing, Not yet reviewed

#151 Release 7.1.0
  CHANGELOG.md
  metadata.json
Labels: Needs testing, Not yet reviewed, skip-changelog
